# Generated by Django 2.2.28 on 2024-03-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_map', '0002_auto_20240318_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
