# Generated by Django 2.2.28 on 2024-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_map', '0004_auto_20240318_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantowner',
            options={'verbose_name_plural': 'Restaurant Owners'},
        ),
        migrations.AddField(
            model_name='restaurantowner',
            name='restaurant_name',
            field=models.CharField(default='Your Restaurant', max_length=128),
        ),
    ]
