# Generated by Django 2.2.28 on 2024-03-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_map', '0005_auto_20240319_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantowner',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='owner_pics'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='reviewer_pics'),
        ),
    ]
