# Generated by Django 2.2.28 on 2024-03-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_map', '0002_auto_20240318_1907'),
        ('meal_map', '0006_auto_20240319_1355'),
    ]

    operations = [
    ]
